name: Publish repository as Zip

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-attach:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create zip of repository
        run: |
          zip -r openeo-${{ github.event.release.tag_name }}.zip . -x '*.git*' '.github*'

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: openeo-${{ github.event.release.tag_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
